tomasfarias/airflow-dbt-python

- airflow_dbt_python/operators/dbt.py
- pyproject.toml
Small bug is causing DAGs to fail rendering since template fields are missing. So we set them for each class to ensure they exist.
>  fix: Set template fields for each operator 

- airflow_dbt_python/hooks/dbt.py
- pyproject.toml
Aiflow v1's `BaseHook` has the following `__init__` signature:
```python
def __init__(self, source):
```
This `source` argument is not used by us (or anywhere else in `BaseHook`), so we override it to not require it.
> fix: Override BaseHook init to support Airflow v1

- README.md
- airflow_dbt_python/__version__.py
- airflow_dbt_python/hooks/dbt.py
- airflow_dbt_python/hooks/s3.py
- airflow_dbt_python/operators/dbt.py
- examples/dbt_project_in_s3_dag.py
- pyproject.toml
- tests/hooks/dbt/test_dbt_generate.py
- tests/hooks/s3/test_dbt_s3_hook.py
- tests/operators/test_dbt_deps.py
- tests/operators/test_dbt_docs_generate.py
Support for dbt docs generate itself is pretty trivial as we only needed a
new configuration and dbt docs generate does not take many
configuration arguments. The biggest challenge of supporting dbt docs generate
is solving the issue of running dbt docs generate in a temporary
directory: there isn't much sense in executing dbt docs generate if we
cannot use the results of the execution. The alternative of pushing
the dbt artifacts to XCom is, of course, still available, but I wanted
to use this an excuse to develop something else.
So, we also added a push_dbt_project method to our S3
hook. This method is called right before exiting the temporary
directory, and can be controlled with a push_dbt_project argument to
the operator. The argument is by default True for the new …
> feat(operator): Add new operator for dbt docs generate

- .pre-commit-config.yaml
- airflow_dbt_python/hooks/s3.py
- airflow_dbt_python/operators/dbt.py
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/hooks/s3/test_dbt_s3_hook.py
- tests/operators/test_dbt_deps.py
DbtDepsOperator could have unintended side-effects if it were to
modify files outside of the packages directory. For this reason, we
added a new test, and extended existing tests to ensure no files are
changed in a dbt project outside of the dbt packages directory.
This should provide more guarantees about the behavior of the
operator, especially when looking to push back files to S3.
Moreover, this PR introduces a new parameter: `replace_on_push`.
Setting it to False will skip any S3 uploads when a key
already exists. This is useful to guarantee no unexpected files are
changed.
I'm still not super convinced about the solution as ideally
we would like partial replacing; only replacing changed files would be
ideal. This is hard to do with compressed projects, as it would
require …
> Testing improvements and new replace_on_push parameter

- .github/workflows/test.yaml
- poetry.lock
- pyproject.toml
Since we wish to support all MWAA supported versions of Airflow,
this requires supporting both 1.10.12 and 2.X releases. However, There
are several conflicting dependencies between dbt-core and
apache-airflow. None of the conflicts should break us, but they do
make dependency resolution impossible, which means airflow-dbt-python
cannot be installed.
For this reason we have removed the dependency to
apache-airflow. Assuming that as an Airflow operator we are always
installing airflow-dbt-python in an environment that already has
Airflow installed, this shouldn't cause any issues in production
deployments.
Moreover, this makes testing multiple Airflow versions easier as we
can pre-install apache-airflow.
> Make apache-airflow not required 

- airflow_dbt_python/operators/dbt.py
Adding vars to the list of template_fields on the DbtBaseOperator.
This will allow passing variables to the operator from the dag_run.conf
> Closes #10 Adding vars as a template_field to DbtBaseOperator

- airflow_dbt_python/__version__.py
- pyproject.toml
I was hesitant to release v0.13.0 due to how much code we refactored. But I've changed my mind: pre-release has been out for a week, and it has started to block other issues.
> chore: Bump minor version

- airflow_dbt_python/__version__.py
- airflow_dbt_python/hooks/backends/s3.py
- pyproject.toml
- tests/hooks/dbt/backends/test_dbt_s3_backend.py
- tests/operators/test_dbt_clean.py
- tests/operators/test_dbt_docs_generate.py
S3 files were uploaded to incorrect keys when running Airflow 2. This
was caused by differences between Airflow 1.10 and Airflow 2: the
latter assumes that when passing both bucket_name and key that the key
is to be taken as it is, where as the former seemed to work even when
the key contained the full url.
Now, we do the parsing and splitting ourselves. We would just set
bucket_name to None, however with Airflow 2.0 the upload function
checks for the presence of the bucket_name argument, to decide whether
to parse the url, not if it's set to None (I think this may be a bug).
> fix(s3): Split bucket name and key before uploading

- airflow_dbt_python/hooks/dbt.py
- tests/hooks/dbt/test_dbt_run.py
dbt handles exceptions raised by task.run() with the track_run context
manager. We are also doing the same thing. The problem is that some
exceptions, like FailedToConnectException, are failing silently (at
least for us, CLI users do see a log) and are not re-raised by
dbt.
Continuing with execution would lead to an UnboundLocalError as
we don't account for results never being set. To address this we
preemptively set results to None before running a task.
Closes #49
> fix: Set results before running task to avoid UnboundLocalError

- .gitignore
- README.md
- docs/example_dags.rst
- examples/airflow_connection_target_dag.py
- examples/basic_dag.py
- examples/complete_dbt_workflow_dag.py
- examples/dbt_project_in_s3_dag.py
- examples/use_dbt_artifacts_dag.py
- pyproject.toml
- tests/conftest.py
- tests/dags/test_dbt_dags.py
Closes #55 
This PR adds more integral testing by defining DAGs with `Dbt*` operators, triggering runs, and checking outputs. We test both the context manager way of defining a dag as well as the TaskFlow API.
As I was working on this I noticed the example DAGs were actually broken 😅. So this PR also fixes them.
> test(dags): Add tests for dbt operators in DAGs

- airflow_dbt_python/hooks/dbt.py
- airflow_dbt_python/operators/dbt.py
- poetry.lock
- pyproject.toml
- tests/operators/test_dbt_seed.py
> feat(dbt): Support for dbt-core >= 1.1

- .github/workflows/test.yaml
- README.md
- airflow_dbt_python/__version__.py
- docs/getting_started.rst
- pyproject.toml
Closes #59
I'll consider Python 3.10 supported if we can get the testing pipeline to pass. That being said, I'm seeing issues with `apache-airflow==1.10.15` and `apache-airflow==2.0.2`, so I'll mention in the docs Python 3.10 is only tested in  `apache-airflow>=2.2`. Our dependencies already require `apache-airflow>=2.2`.
> feat: Support Python 3.10

- airflow_dbt_python/__version__.py
- airflow_dbt_python/hooks/dbt.py
- pyproject.toml
- tests/conftest.py
- tests/hooks/dbt/test_dbt_hook_configs.py
- tests/hooks/dbt/test_dbt_run_operation.py
- tests/operators/test_dbt_run_operation.py
When running a macro without arguments using DbtRunOperationOperator
the args parameter was set to None. However, dbt always expects a
string. So, now we always cast to string and have set the default to
"{}", that matches dbt's default.
Closes #65
> fix: Correct casting of run-operation args to str

- poetry.lock
- pyproject.toml
airflow-dbt-python has a rather complicated build process (I'm thinking how to make this easier) that relies on new poetry features added in 1.2.0. Before, we relied on an alpha version release, but now that the stable 1.2.0 version is out, we can upgrade the required poetry versoin.
> feat: Update poetry to v1.2.0

- .github/workflows/test.yaml
Moving forward, the testing strategy will change. We will be targeting all minor Python versions supported by dbt (>=3.7, <3.11 as of writing this) and the following Airflow versions:
* Latest MWAA supported version (2.2.2 as of writing).
* Latest available version (2.4.* as of writing).
For the time being, I'm keeping support for 1.10.15, although it's likely that won't last for much longer. There isn't much of a reason to be on Airflow 1 now that MWAA supports >2, which was the original reason why we had support for 1.10.15.
This PR simplifies our GitHub actions CI/CD workflow to remove some extra steps and rely on matrix variables instead.
> chore(cicd): Alter testing strategy in GitHub Actions

- examples/use_dbt_artifacts_dag.py
- tests/conftest.py
- tests/dags/test_dbt_dags.py
- tests/operators/test_dbt_test.py
In an effort to try and isolate the issue reported in #79, we add a new DAG to the integration tests that setups an Airflow connection in a similar fashion to the example DAG.
The test is passing, however once more details are provided, it may be extended to attempt to replicate the issue.
> feat(test): Add DAG that uses Airflow connection to tests

- .pre-commit-config.yaml
`flake8` has been [migrated to GitHub](https://twitter.com/codewithanthony/status/1378746934928699396), and the GitLab repository has been deleted.
For existing contributors, `pre-commit` still works because a virtualenv with the current configured `flake8` version is cached. However, cleaning up the cache and trying to run `pre-commit run` is enough to reproduce the issue.
> chore: Update flake8 pre-commit URL to point to GitHub repository

- airflow_dbt_python/operators/dbt.py
For complex DAGs, the import time added by this library could generate `DagBag` import timeouts if the configured value is low enough. An Airflow documented best practice is to
[avoid heavy Python code](https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html#top-level-python-code) that runs on DAG and Operator creation, and `dbt` imports are slow, based on profiling.
Profiling can be easily run locally, with the following command:
```shell
python -X importtime -c "from airflow_dbt_python.operators.dbt import DbtRunOperator" 2>import-times.log
```
And then parsed using a tool like [tuna](https://github.com/nschloe/tuna).
Before this change, the operator import takes ~1.37s, which is reduced to ~0.25s with this fix.
It's important to note that, from those 0.25s, more than …
> fix: Avoid heavy top-level imports in operators

- airflow_dbt_python/hooks/dbt.py
- airflow_dbt_python/operators/dbt.py
- airflow_dbt_python/utils/__init__.py
- airflow_dbt_python/utils/enums.py
After a previous commit [1] improving import time on operator import, this commit fixes the import time issues when instantiating any of the dbt operators.
The main issue still present was the enum imports in the operator constructors, which make DAGs slow to import any time they instantiated one of them.
Profiling can be easily run locally, with the following command:
```shell
python -X importtime -c "from airflow_dbt_python.operators.dbt import DbtRunOperator; DbtRunOperator(task_id='test')" 2>import-times.log
```
[1] https://github.com/tomasfarias/airflow-dbt-python/commit/67c8d7866235e105675bd208659aac2ccc26070e
> fix: Avoid heavy imports in operator constructor

- airflow_dbt_python/__version__.py
- airflow_dbt_python/hooks/dbt.py
- pyproject.toml
dbt v1.4.1 replaced `InternalException` for `DbtRuntimeError`. `airflow-dbt-python` is currently underworking heavy refactoring in a different branch, but this issue is relatively simple to fix and makes us unusable, so it requires a quick patch. 
Closes #91
> fix: Conditional import for different dbt exceptions

- .github/workflows/ci.yaml
- airflow_dbt_python/hooks/dbt.py
- airflow_dbt_python/operators/dbt.py
- airflow_dbt_python/utils/env.py
- tests/conftest.py
- tests/hooks/dbt/test_dbt_hook_base.py
- tests/hooks/dbt/test_dbt_run.py
- tests/hooks/dbt/test_dbt_seed.py
- tests/operators/test_dbt_run.py
- tests/utils/test_configs.py
- tests/utils/test_env.py
Closes #88 
Environment variables are used by dbt to template configuration files. Although users can now modify the environment of Airflow workers, there is no interface for them to do it in airflow-dbt-python.
This commit adds an env_vars argument that can take a dictionary of environment variables to set during dbt execution. This can be useful for folks who wish to keep their profiles.yml templates.
> feat: Provide env_vars to update environment variables

- pyproject.toml
Pre-release v1.0.0 versions have been available since 2023-02-20, and no breaking bugs have been reported, so this PR finally bumps the version to v1.0.0 for a full-fledged release. I feel confident in the API we have built, and if we waited for the work still to do there would never be a release.
The release notes will comment on breaking changes and recommend users to test out v1 in case they didn't already test the pre-release versions.
Some features didn't make it in and are planned for v1.1, both of them related to supporting different sources for artifacts (and could actually be seen as one two sides of one new feature):
* https://github.com/tomasfarias/airflow-dbt-python/issues/90
* https://github.com/tomasfarias/airflow-dbt-python/issues/67
> chore: Version v1.0.0 bump

- airflow_dbt_python/hooks/remote.py
This change makes the library only import the hook it's going to need based on the remote scheme.
As it is currently implemented, an environment that uses a S3 remote fails if it doesn't have the `ssh` Airflow provider installed:
```
Traceback (most recent call last):
File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow_dbt_python/hooks/dbt.py", line 126, in get_remote
return self.remotes[(scheme, conn_id)]
KeyError: ('s3', None)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow_dbt_python/hooks/dbt.py", line 300, in dbt_directory
project_dir, profiles_dir = self.prepare_directory(
File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow_dbt_ …
```
> fix: Conditionally import required hook

- .github/workflows/ci.yaml
- airflow_dbt_python/hooks/git.py
- airflow_dbt_python/hooks/remote.py
- airflow_dbt_python/utils/url.py
- poetry.lock
- pyproject.toml
- tests/hooks/test_git_hook.py
As per #112, we are dividing the work of supporting auth for git remotes into two:
* The first part, this PR, deals with supporting basic authentication with not many changes.
* The second part, involves more refactoring work to split up the git hook into `DbtSSHGitRemote` and `DbtHTTPGitRemote`. This split will allow us to have separate connection types for both schemes (and get rid of a big `if`).
The reason why this is being split into two is that we have a chance to deliver value just with the first part, and tackle any bugs that may be easier to solve before we dive into refactoring.
> feat: Support for basic auth in git remotes

- .github/workflows/tagged_release.yml
Closes #114 
Also includes:
* A name change now that I have switched to fine-grained token for deployment. 
* A fix on the `IS_PRERELEASE` check.
> feat: Check git tag matches version on release

- airflow_dbt_python/operators/dbt.py
- airflow_dbt_python/utils/configs.py
- tests/operators/test_dbt_list.py
Although unable to reproduce #128, this looks like a typo in the template field. Let's see if fixing it causes any issues.
If tests pass, then we'll close #128 until further information.
>  fix: Typo in template field

- .github/workflows/tagged_release.yml
As part of our continuous deployment workflow, we have a step that
waits for our CI workflow to finish successfully. However, the action
used to wait for the CI workflow doesn't fail on a timeout, it just
sets an output variable.
So, we should have an extra step to check the output and fail
appropriately.
Finally, we shouldn't be timing out at all. CI takes roughly 20
minutes, so I'm bumping the timeout to an hour to make sure we have
plenty of time to wait for that.
> fix(cd): Properly fail deploy if CI fails

- .pre-commit-config.yaml
- airflow_dbt_python/hooks/fs/git.py
- tests/hooks/test_git_hook.py
Dulwich expects repo branch to be bytes, not str. This seems to be a
gap in the type hinting of dulwich, as other arguments to client.clone
can be passed as str.
Regardless, as a workaround, we can encode branch as bytes.
> fix(git-hook): Pass branch as bytes

- README.md
- airflow_dbt_python/operators/dbt.py
- airflow_dbt_python/utils/configs.py
- docs/development.rst
- examples/readme_example_dbt_dag.py
- tests/conftest.py
- tests/operators/test_dbt_build.py
- tests/operators/test_dbt_compile.py
- tests/operators/test_dbt_run.py
- tests/operators/test_dbt_seed.py
- tests/operators/test_dbt_snapshot.py
- tests/operators/test_dbt_source.py
- tests/operators/test_dbt_test.py
Around dbt version 1.5, the selector_name argument got renamed to
simply selector. Our configuration already supports it, so we should
use it everywhere and treat selector_name as a backwards compatible
alias.
Moreover, selector is always a string, and not a list of strings as it
was typed in the DbtRunOperator.
> fix: Use selector instead of selector_name

- .github/workflows/ci.yaml
- uv.lock
dbt-core 1.10 has been out for some time now. Let's ensure we can support it by building `airlfow-dbt-python` with dbt-core 1.10 and running it in CI. This drops 1.8 from the testing pipeline as I only want to keep the last 2 versions to avoid CI getting too long.
This does not include support for new features (like `--sample`) just ensuring we are compatible.
> chore: Build with dbt-core 1.10

- airflow_dbt_python/hooks/target.py
- tests/hooks/test_trino.py
Add a `DbtTrinoHook` to `airflow_dbt_python/hooks/target.py` for dbt-trino.
- Auto-registered via metaclass with `airflow_conn_types=('trino',)`
- Extras-first behavior: supports legacy 2.2.0 style where everything is in `conn.extra`
- Maps `database` → `catalog` for dbt-trino; explicit `catalog` overrides the fallback
- Accepts host/port/user/password/schema from extras to keep 2.2.0 compatibility
- Optional passthroughs: `session_properties`, `http_headers`, `role`, `client_tags`, `source`
```json
{
"type": "trino",
"method": "ldap",
"user": "usert",
"password": "pass",
"host": "trino.example",
"port": 443,
"http_scheme": "https",
"database": "example",
"schema": "example",
"verify": false
}
```
- `tests/hooks/test_trino.py` validates:
- extras-only mapping …
> feat: add DbtTrinoHook
